---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sysdigcloud-anchore-reports
  labels:
    app: sysdigcloud
    role: anchore-reports
data:
  config.yaml: |
    service_dir: /anchore_service
    tmp_dir: "/tmp"
    log_level: INFO
    cleanup_images: true

    allow_awsecr_iam_auto: false
    host_id: ${ANCHORE_POD_NAME}
    internal_ssl_verify: false
    auto_restart_services: false
    license_file: "/license/license.yaml"

    metrics:
      enabled: false

    credentials:
      database:
        db_connect: "postgresql://${ANCHORE_DB_USER}:${ANCHORE_DB_PASSWORD}@${ANCHORE_DB_ENDPOINT}/${ANCHORE_DB}"
        db_connect_args:
          timeout: 120
          ssl: false
        db_pool_size: 50
        db_pool_max_overflow: 70

    services:
      reports:
        enabled: true
        require_auth: true
        endpoint_hostname: anchore-reports
        listen: '0.0.0.0'
        port: 8558
        enable_graphiql: true
        enable_data_ingress: true
        cycleTimers:
          # images and tags synced every 10 minutes
          reports_data_load: 600
          # policy evaluations and vulnerabilities refreshed every 2 hours
          reports_data_refresh: 7200
          # metrics generated every hour
          reports_metrics: 3600
