---
apiVersion: v1
kind: Service
metadata:
  name: anchore-reports
  labels:
    app: sysdigcloud
    role: anchore-reports
spec:
  type: ClusterIP
  ports:
    - name: reports-api
      port: 8558
      protocol: TCP
      targetPort: 8558
  selector:
    app: sysdigcloud
    role: anchore-reports
